# @package _global_
model:
  name: BdeMile
  hidden_layers: [16, 16]
  n_members: 8
  n_epochs: 200
  lr: 0.001
  weight_decay: 0.0001
  warmup_steps: 5000
  n_samples: 500
  n_thinning: 2
  patience: 10
  validation_split: 0.15
  seed: 0
  activation: relu
  L: null
  bond_dim: null
  init_strength: null
